# Generated by Django 6.0.2 on 2026-02-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('NOT_PLACED', 'Not Placed')], default='PLACED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('career_interest', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
