# Generated by Django 6.0.2 on 2026-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_alumniprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='current_placement',
            field=models.TextField(blank=True, help_text='Current placement details outside college'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='is_placed_in_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='placement_record',
            field=models.TextField(blank=True, help_text='Placement record while in college'),
        ),
    ]
