# Generated by Django 6.0.2 on 2026-03-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alumniprofile_branch_alumniprofile_current_placement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumniprofile',
            old_name='is_placed_in_college',
            new_name='campus_placed',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='current_placement',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='placement_record',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CampusPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=50)),
                ('placement_year', models.IntegerField()),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campus_placement', to='profiles.alumniprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_role', models.CharField(max_length=100)),
                ('ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('experience_description', models.TextField(blank=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.alumniprofile')),
            ],
        ),
    ]
