# Generated by Django 6.0.2 on 2026-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_studentprofile_branch_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
