# Generated by Django 6.0.2 on 2026-03-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Link to apply for the job', max_length=500, null=True),
        ),
    ]
